version: '3'
services:
  backend:
    build: .
    ports:
      - 8000:8000
    env_file:
      - ./envs/.dev.env
    command: "python manage.py runserver 0:8000"
    depends_on:
      - postgres
    volumes:
      - ./backend:/backend
      - static-files:/static-files
      - media-files:/media-files

  postgres:
    image: postgres:latest
    ports:
      - '5432:5432'
    env_file:
      - ./envs/.dev.env
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
  media-files:
  static-files:
